Repository googleapis/google-cloudevents-nodejs, pull requests merged in 2020-12, with the labels that each got.

#74 docs: add generated docs
  README.md
  package.json
  reference.md
  tools/docs.ts
Labels: api: eventarc, automerge, cla: yes

#73 Update release-please.yml
  .github/workflows/release-please.yml
Labels: api: eventarc, cla: yes

#76 feat(build): split release PR and publish step
  .github/workflows/release-please.yml
Labels: api: eventarc, automerge, cla: yes

#78 build: only label PR if a PR was opened
  .github/workflows/release-please.yml
Labels: api: eventarc, cla: yes, kokoro:force-run

#79 chore: run the generator, dec 2, 2020
  cloud/audit/v1/LogEntryData.ts
  cloud/cloudbuild/v1/BuildEventData.ts
  cloud/firestore/v1/DocumentEventData.ts
  cloud/pubsub/v1/MessagePublishedData.ts
  cloud/scheduler/v1/SchedulerJobData.ts
  cloud/storage/v1/StorageObjectData.ts
  firebase/analytics/v1/AnalyticsLogData.ts
  firebase/auth/v1/AuthEventData.ts
  firebase/database/v1/ReferenceEventData.ts
  firebase/remoteconfig/v1/RemoteConfigEventData.ts
Labels: api: eventarc, automerge, cla: yes

#81 fix: fix the build release workflow
  .github/workflows/release-please.yml
Labels: api: eventarc, automerge, cla: yes
